### ISSUE TITLE
Lvm<-> BRTFS restoration support

### ISSUE THREAD

**Issue by tlaurion** [tasket/wyng-util-qubes#10]
Reasoning is that BRTFS is faster and will most probably become the default under QubesOS

Read on bees!!!! Deduplication on restoration side of archives!
 https://forum.qubes-os.org/t/about-btrfs-with-compression-in-qubes-os/19707/10?u=insurgo

Replaces issue https://github.com/tasket/wyng-backup/issues/166

**Comment by tasket** [comment]
FWIW, Wyng does perform backups noticeably faster with Btrfs.  You're probably right that Qubes would (should) move to Btrfs or XFS as default, as they're also more stable than TLVM.

I'll add some clarification to the Readme here, so there is no doubt that wyng-util-qubes operates at the Qubes VM (and Qubes storage pool) level.  Therefore, moving between TLVM and reflink should be transparent and very easy for the user.

**Comment by tlaurion** [comment]
Let me know when this is implemented I will be your first beta tester

**Comment by tlaurion** [comment]
> Let me know when this is implemented I will be your first beta tester

@tasket does https://github.com/tasket/wyng-util-qubes/commit/182494b28c8bf2d3841513d83e55d5f0876d8913 mean that I can test it?!?

**Comment by tasket** [comment]
Not for reflink, no.  Reflink path handling still needs work.

**Comment by tasket** [comment]
@tlaurion FYI the 09beta branch has direct support for Btrfs/reflink now.  The only thing left is translating between reflink and lvm paths.

**Comment by tlaurion** [comment]
> Reasoning is that BRTFS is faster and will most probably become the default under QubesOS
> 
> Read on bees!!!! Deduplication on restoration side of archives!
>  https://forum.qubes-os.org/t/about-btrfs-with-compression-in-qubes-os/19707/10?u=insurgo
> 
> Replaces issue https://github.com/tasket/wyng-backup/issues/166
> 
> 

Seems like qubesos disagrees in those claims still though https://github.com/QubesOS/qubes-issues/issues/6476

Idea now is staying TLVM and trying to figure out how to go zfs copying Ubuntu way of doing things with @Rudd-O amazing articles, while I will try to make bees spec file for fedora 37 when I have free time again.
