### ISSUE TITLE
README and --help need better explanation for --dest 

### ISSUE THREAD

**Issue by gasull** [tasket/wyng-util-qubes#12]
I'm trying to create my first `wyng` backup, saving it in the `/media/backups/` directory in the sys-backup VM.  I think the command is somewhat like this:

```bash
sudo wyng-util-qubes backup --dedup --dest <DEST> --includes browsing vault
```

Where `browsing vault` are the two VMs I want to backup.

What should be in `<DEST>` if the destination is `/media/backups/` in the sys-backup VM?

This is isn't just a support question.  I think the README and `--help` option don't explain this enough.

**Comment by tasket** [comment]
@gasull Hi... You'll need to think of a name for the wyng archive at the desired backup path, which must be created with `wyng arch-init`.  The `--dest` parameter syntax & requirements follow the wyng parameter of the same name, so some familiarity with wyng itself is suggested.

Starting out would look like:
```
sudo wyng arch-init --dest file:/media/backups/laptop1.backup

sudo wyng-util-qubes backup browsing vault --pool=vm-pool --dest=file:/media/backups/laptop1.backup
```

This assumes that your VMs are located in Qubes 'vm-pool'. I'm considering an approach that would make specifying the pool unnecessary (at least for `backup` mode) but for now it should be included on the `wyng-util-qubes` command line.

I've just updated main branch with the most recent code from August, and added some examples to the README which starts with creating an archive.

**Comment by tasket** [comment]
And... just noticed you are backing up to a VM, so my example above is wrong.  It should be:

```
sudo wyng arch-init --dest qubes://sys-backup/media/backups/laptop1.backup

sudo wyng-util-qubes backup browsing vault --pool=vm-pool --dest=qubes://sys-backup/media/backups/laptop1.backup
```

@gasull

**Comment by gasull** [comment]
> This assumes that your VMs are located in Qubes 'vm-pool'.

How can I know if my VMs are located in Qubes 'vm-pool'?

>  I'm considering an approach that would make specifying the pool unnecessary (at least for backup mode) but for now it should be included on the wyng-util-qubes command line.

Until then I think the README should explain how to find if the VMs are located in Qubes 'vm-pool'.  I've been using Qubes OS for years and `wyng` makes me feel like a total newbie because it requires knowing too much about the internals.

Thank you for your help.

**Comment by tasket** [comment]
The example does show how to find the pool info, but I get what you're saying. Thankfully it isn't too esoteric a subject, since the Qubes disk space systray widget shows the same info.

For the near future I can automatically get the pool for backups, but for restores the storage pool may be required in some cases.

**Comment by gasull** [comment]
> The example does show how to find the pool info

I might be missing something that's in front of my eyes, but I'm going to need you to spoon-feed this to me:

**How do I find where my VMs are located?**

From the README:

> ```
> Qubes local storage pools:
> varlibqubes             : file-reflink, /var/lib/qubes
> vm-pool                 : thin_lvm, qubes_dom0/vm-pool
> ```

I see a directory per VM in `/var/lib/qubes/appvms/` but they only contain one file each: `firewall.xml`.

I don't know what `vm-pool` is.

**Comment by tasket** [comment]
> How do I find where my VMs are located?

This is one of those "if you have to ask..." questions. The solution mainly lies with Qubes, but I digress.

The best thing to do here would be to change the readme to mention in passing that the default pool will be used, but not show --pool option in the examples.  OTOH, people who have set up other pools will be aware of them and that they have placed VMs there.

Thanks for bringing this up!
