### ISSUE TITLE
KeyError when VM template is a disposable VM

### ISSUE THREAD

**Issue by gasull** [tasket/wyng-util-qubes#15]
```Python
Traceback (most recent call last):
  File "/usr/local/bin/wyng", line 4668, in <module>
    monitor_send(storage, aset, selected_vols, monitor_only=False)
  File "/usr/local/bin/wyng", line 3402, in monitor_send
    = storage.prep_snapshots(storage, aset, datavols, monitor_only,
  File "/usr/local/bin/wyng", line 2594, in prepare_snapshots_lvm
    if not exists(vpath := other_vols.get(datavol) or lvols[datavol].path):
KeyError: 'vm-sys-firewall-private'
```

My guess is that this is happening because the sys-firewall template is a Debian disposable.

**Comment by gasull** [comment]
It's also happening to me for sys-net, that also has a disposable template.

**Comment by tasket** [comment]
@gasull What is the version-date of wyng here?

**Comment by gasull** [comment]
> @gasull What is the version-date of wyng here?

I don't how how to see the `wyng` version even looking at the code.  This is the last commit according to `git log`:

https://github.com/tasket/wyng-backup/commit/121e6d2583d26f1fe8caca7d9e7cb3bd0cf2da13

Is the version too old?

And this is the `wyng-util-qubes` version:

```
wyng-util-qubes v0.7beta rel 20230721
```

**Comment by tasket** [comment]
@gasull This should be fixed in today's `wyng` commit in 08wip branch.

Note I am also going to exclude dispVMs in `wyng-util-qubes` by default, but also adding an experimental option --include-disposable.
