### ISSUE TITLE
Handle disposable vms correctly

### ISSUE THREAD

**Issue by tasket** [tasket/wyng-util-qubes#22]
Some errors have cropped up when backing up disposable templates.

Research, test and implement fixes.

**Comment by tasket** [comment]
@kennethrrosen Backup and restore of dispvm templates are now working for me. See the current update in the util's 09beta branch.

**Comment by UndeadDevel** [comment]
Using `--include-disposable` doesn't seem to work for me, it will output:
```
Preparing snapshots in '/dev/qubes_dom0/'...
Warning: Local '/dev/qubes_dom0/vm-dvm1-private' does not exist!
Warning: Local '/dev/qubes_dom0/vm-dvm2-private' does not exist!
Warning: Local '/dev/qubes_dom0/vm-dvm-for-printing-private' does not exist!
Warning: Local '/dev/qubes_dom0/vm-dvm-for-printing-gnome-private' does not exist!
Warning: Local '/dev/qubes_dom0/vm-sys-firewall-private' does not exist!
Warning: Local '/dev/qubes_dom0/vm-sys-thunderbolt-private' does not exist!
Warning: Local '/dev/qubes_dom0/vm-sys-usb-private' does not exist!
Warning: Local '/dev/qubes_dom0/vm-veracrypt-private' does not exist!
```
And then just skip those (my expectation was that it still backs up the VM settings, for example). When listing the VMs in my archive I don't see the DVMs listed.

**Comment by tasket** [comment]
@UndeadDevel I think what you're saying is: The desired behavior backs up the disp template data, and also the derived dvm definition but not its data.  That makes sense.

It does require a bit more sophisticated handling in the util, and it may take some time to implement.

**Comment by tasket** [comment]
@UndeadDevel The util update in the wip branch will now restore dispvms.  The `--include-disposable` option includes dispvms when inclusion is implicit (such as specifying only `--session` which implies all vms in the session); otherwise it isn't needed and dispvms will always be restored if you specify their names.

Because they have no indexing in Wyng, dispvms will only show in a `list` if you specify `--session` so it can use a particular qubes.xml instance as an index.  Also, since they have no data volumes, the prune, verify and delete commands don't recognize dispvms.

**Comment by tasket** [comment]
Implemented.
