### ISSUE TITLE
Template VM not restored from wyng backup

### ISSUE THREAD

**Issue by UndeadDevel** [tasket/wyng-util-qubes#23]
This is with `wyng-util-qubes v0.9beta rel 20240424` and `Wyng 0.8beta release 20240423` on a pretty standard configured Qubes 4.2 system (thin-LVM) where I had been using `wyng-util-qubes` for incremental backups a few times and now wanted to test restoring from backup. I had not been using deduplication. I had not been using `wyng` directly, only via the Qubes wrapper.

So I wanted to revert some template changes, used `qvm-volume revert` and noticed that the oldest snapshot already had the undesirable changes; hence decided to restore from backup (I did not revert back to a different snapshot with `qvm-volume`, so it was now at the oldest).

Command:
```
[user@dom0 ~]$ sudo wyng-util-qubes --dest=qubes://path/to/backups/mybackup.backup restore debian-12-xfce
wyng-util-qubes v0.9beta rel 20240424
Enter passphrase: 

VMs selected: debian-12-xfce
```
No error messages, so I thought it restored it fine, but when checking the template it seemed to not have been changed at all.
So I renamed the template (and shut down all qubes based on it) and tried again (same command and output as above), but again nothing happened; no template with the previous name was restored.

I ended up restoring from a "normal" Qubes backup, which worked fine.

**Comment by tasket** [comment]
@UndeadDevel Probably the return code from this bug is '2' (if you run `echo $?` right after Wyng it will display the code).

In that case, it should already be fixed in the Wyng 08beta [branch](https://github.com/tasket/wyng-backup/tree/08beta).

**Comment by tasket** [comment]
@UndeadDevel There is another bug that was fixed in the util's 09beta branch today fyi.  It would be great if you could quickly test these to see if the fixes worked for you.

**Comment by UndeadDevel** [comment]
@tasket Confirmed fixed :+1:
