### ISSUE TITLE
expose tag-with-comment capability from Wyng

### ISSUE THREAD

**Issue by kennethrrosen** [tasket/wyng-util-qubes#26]
Wyng has a tag-with-comment capability. Exposing this feature for Qubes users would be beneficial in identifying deduplicated backup changes to identify which session the user may wish to restore. The until could prompt a user for brief comment before starting each backup.

Say a VM called `comms` was updated from Fedora-38 to Fedora-39 through an in-place upgrade. It had been backed up before. Now, after the upgrade, a user might tag this session as `comms f38 > f39` during the backup. If an issue arises in F39 and the user knows F38 was stable, they can find the session before the update and restore.

**Comment by tasket** [comment]
Basic tag capability has been added:

* Tags can be assigned with a `backup` session like so: `wyng-util-qubes --dest=<url> -w tag=tname1 -w "tag=tname2, This is a test." backup <vms>`.  They can also be input interactively with `-w tag=@`.
* The `list --session=<session id>` form of list will display the tags in the specified session.
* Won't work correctly with Wyng releases before 20240526.

This update is in the beta branches of both projects.

@kennethrrosen @undeaddevel @tlaurion
