### ISSUE TITLE
Use progress bar/status as default

### ISSUE THREAD

**Issue by kennethrrosen** [tasket/wyng-util-qubes#28]
Currently, `wyng` will display progress using a combination of `-u -verbose`, but not with `-u` alone. There is concern that system logs may become overloaded with progress notifications if the util or `wyng` is run from crond or system unit. Showing backup and restoration progress is essential to time-management and user-friendliness. 

Thus, the `-u` flag should default to showing progress, however minimal, with something akin to `-u -quiet` offering users a less verbose/log-overwhelming feature.

**Comment by tasket** [comment]
I'm not sure about the question of defaults. There are many copying and archival tools (like Duplicity) that will not show progress indicators unless asked, even when they have interactive terminal sessions.

How do you feel about showing progress in 10% increments?

**Comment by kennethrrosen** [comment]
Anything, even an ellipsis, would do, but at present there is only a colon until the backup or restore is completed. I also realize I'm generalizing, but in my mind, to serve as a potential qvm-backup replacement, users should see the progress from the outset. I do realize things like --show-progress are often not there by default, but I'm thinking of the no-so-tech-savy.

**Comment by tlaurion** [comment]
> Anything, even an ellipsis, would do, but at present there is only a colon until the backup or restore is completed. I also realize I'm generalizing, but in my mind, to serve as a potential qvm-backup replacement, users should see the progress from the outset. I do realize things like --show-progress are often not there by default, but I'm thinking of the no-so-tech-savy.

Design decision is relevant to costs of producing that progress report?

**Comment by tasket** [comment]
@kennethrrosen @tlaurion The latest updates in Wyng and util betas are more consistent now. Unattended mode uses only a progress bar (until the end), and the util doesn't force -u for either backup or restore.

**Comment by tasket** [comment]
Also, it should be noted that `-u` is automatic in Wyng when no tty is present, such as when its run from cron or system.
