### ISSUE TITLE
LVM backups restoration on Q4.2.1 BTRFS partition scheme failed

### ISSUE THREAD

**Issue by tlaurion** [tasket/wyng-util-qubes#30]
```
sudo wyng-util-qubes --dest qubes-ssh://wyng-wdcloud:root@Insurgo-LabRouter/mnt/Backups/nv41 restore qusal --debug -u
Wyng 0.8beta release 20240525
Local storage is offline: '/var/lib/qubes' is not a subvolume.
Encrypted archive 'qubes-ssh://wyng-wdcloud:root@Insurgo-LabRouter/mnt/Backups/nv41' 
Last updated 2024-05-29 18:06:09.382499 (-04:00)

 Offline volumes: vm-qusal-private
wyng-util-qubes v0.9beta rel 20240515
['/usr/sbin/wyng', '--dest=qubes-ssh://wyng-wdcloud:root@Insurgo-LabRouter/mnt/Backups/nv41', '-u', '--json', 'list']
['/usr/sbin/wyng', '--dest=qubes-ssh://wyng-wdcloud:root@Insurgo-LabRouter/mnt/Backups/nv41', '-u', '-u', '--quiet', '--save-to=/tmp/wuquec6n48h/qmeta.tgz', '--session=20240529-175037', 'receive', 'wyng-qubes-metadata']
['tar', '-xzf', '/tmp/wuquec6n48h/qmeta.tgz']

VMs matched in session 20240529-175037:
 qusal

Restoring VM data volumes:
JSON:
 {"/var/lib/qubes": [["vm-qusal-private", "appvms/qusal/private.img"]]}
['/usr/sbin/wyng', '--dest=qubes-ssh://wyng-wdcloud:root@Insurgo-LabRouter/mnt/Backups/nv41', '-u', '-u', '--sparse-write', '--local-from=/tmp/wuquec6n48h/wuq_vols.lst', '--session=20240529-175037', 'receive']
Traceback (most recent call last):
  File "/usr/sbin/wyng-util-qubes", line 383, in <module>
    handle_wyng_vol_error(p)
  File "/usr/sbin/wyng-util-qubes", line 148, in handle_wyng_vol_error
    errln = [x.partition("volumes(s)") for x in p.stdout.splitlines() if "volumes(s):" in x]
                                                ^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'splitlines'
```

Good news is that reinstalling into typical LVM Q4.2.1 default partition scheme worked restoring everything without issue!

**Comment by tlaurion** [comment]
I notice that receive is automatically into --sparse-write? Can you refresh my memory on what should be the override if more CPU time is desired and less throughput? I would want to test this over tor hidden service at some point. 

@tasket Thanks!

**Comment by tlaurion** [comment]
wyng

`def receive(args): ... for vol in vols: try: ... recv_vol(vol, args) except Exception as e: print(f"Error receiving volume {vol}: {e}", file=sys.stderr) raise`

Ouptuts to err instead of stdout?
Is that the cause @tasket ?

**Comment by tasket** [comment]
@tlaurion I see what the bug is here; I'm testing possible fixes now.

**Comment by tasket** [comment]
@tlaurion OK try the 09beta branch update.

**Comment by tasket** [comment]
> I notice that receive is automatically into --sparse-write? Can you refresh my memory on what should be the override if more CPU time is desired and less throughput?

You can add `-w sparse` without issue; this should give you the low-bandwidth profile you're looking for (although `-w use-snapshot -w sparse` together may be better; if the correct snapshot isn't available then it should fall back to regular sparse mode).

**Comment by tlaurion** [comment]
> > I notice that receive is automatically into --sparse-write? Can you refresh my memory on what should be the override if more CPU time is desired and less throughput?
> 
> You can add `-w sparse` without issue; this should give you the low-bandwidth profile you're looking for (although `-w use-snapshot -w sparse` together may be better; if the correct snapshot isn't available then it should fall back to regular sparse mode).

@tasket maybe consider a --network option? Or set sparse + use-snapshot when qubes-ssh is used?
