### ISSUE TITLE
Use Qubes backup-restore-in-progress tag

### ISSUE THREAD

**Issue by tasket** [tasket/wyng-util-qubes#34]
Tag VMs in the process of being restored with 'backup-restore-in-progress'.  This will cause Qubes not to start those VMs as long as the tag remains.

Tag is removed on successful completion of restore, or it may also be removed manually with `qvm-tags`.

**Comment by scallyob** [comment]
Oh ok. I just had this problem with a number of my restored qubes, they would not boot with message:
`restore of this domain in progress cannot start`

I used:
`dom0] qvm-tags <qube-name> unset backup-restore-in-progress`

and now they boot. But any idea why the tag wasn't removed by wyng?

**Comment by tasket** [comment]
@scallyob Probably some error occurred before the util could finish (the tag is removed near the end of restore). Did you check the displayed output and the return code?

Right now, the util will stop completely if Wyng reports any error, even if its non-fatal (for example, if only one volume couldn't be restored). I'm working on util changes that properly handle non-fatal errors in that case.

**Comment by scallyob** [comment]
@tasket Yeah, I still have the output on my screen, it seems to have gone through all qubes and then printed "Done."

Then I had it run `wyng arch-check` and they all came back 'OK'

**Comment by tasket** [comment]
@scallyob There are some errors that don't stop the util, but result in the tag left in place (as intended for those cases):

'No volume available for <vm name>'

'Error setting/attaching/removing <object>'

It should also show a list of the VMs that experienced the errors at the end before it says "Done".

If you thing the error is reproducible, or if you still have that terminal output, please open a new issue and I'll look further into it.
