### ISSUE TITLE
bad archive passphrase doesn't return != 0

### ISSUE THREAD

**Issue by tlaurion** [tasket/wyng-util-qubes#35]
`qvm-shutdown --all --wait --exclude xyz && time sudo wyng-util-qubes --dest qubes-ssh://ssh_client:root@server/path/to/archive --authmin 1080 --includes -w remap --dedup --include-disposable=on -wtag='some_tag,some description -wimport-other-from=boot:\|:/dev/boot_partition backup | ts | tee wyng_last_backup_log.txt && poweroff`

Will poweroff if archive passphrase is bad instead of returning to dom0 shell.

**Comment by tasket** [comment]
@tlaurion The util itself is returning a code 3.  But pipe doesn't behave like `&&` as it will mask the exit codes of earlier commands by default.  You probably need to run `set -o pipefail` before running the pipe.
