### ISSUE TITLE
Error: slice indices must be integers or None or have an __index__ method

### ISSUE THREAD

**Issue by tlaurion** [tasket/wyng-util-qubes#9]
Hello @tasket, bumped used versions to 

wyng-util-quebes: v0.5beta rel 20230717
wyng: 0.8beta release 20230717

Today to realize that a lot of things changed, including firectory structure name, -dest format but still confused with teh error i'm currently getting:

```
[user@dom0 ~]$ sudo wyng-util-qubes backup -w dest=file:/media/Backups/QubesOS/wyng.backup040/default/
wyng-util-qubes v0.5beta rel 20230717
Enter passphrase: 
Traceback (most recent call last):
  File "/usr/bin/wyng-util-qubes", line 142, in <module>
    jdata, wvolsessionmap, wvolumemap, wsessionqubes, qube_wvolmap = get_wyng_directory(authmin)
  File "/usr/bin/wyng-util-qubes", line 51, in get_wyng_directory
    for vol, ses in ((x,s) for x,y in wvolumemap.items() for s in y 
  File "/usr/bin/wyng-util-qubes", line 52, in <genexpr>
    if x.startswith("vm-","appvms/","vm-templates/")):
TypeError: slice indices must be integers or None or have an __index__ method
[user@dom0 ~]$ sudo wyng version
Wyng 0.8beta release 20230717
Volume name(s) required for version.
```

I was able to backup currently configured volumes with 
`sudo wyng --all --dest=file:/media/Backups/QubesOS/wyng.backup040/default/ --meta-dir=/var/lib/wyng.backup040/default/ --authmin=10 --local=qubes_dom0/vm-pool send`

**Comment by tlaurion** [comment]
@tasket 

Thought that maybe wyng-util-qubes was confused just like wyng was with lack of `--local` so ran ther following with same result:
```
sudo wyng-util-qubes backup --include -w dest=file:/media/Backups/QubesOS/wyng.backup040/default/ -w local=qubes_dom0/vm-pool
wyng-util-qubes v0.5beta rel 20230717
Enter passphrase: 
Traceback (most recent call last):
  File "/usr/bin/wyng-util-qubes", line 142, in <module>
    jdata, wvolsessionmap, wvolumemap, wsessionqubes, qube_wvolmap = get_wyng_directory(authmin)
  File "/usr/bin/wyng-util-qubes", line 51, in get_wyng_directory
    for vol, ses in ((x,s) for x,y in wvolumemap.items() for s in y 
  File "/usr/bin/wyng-util-qubes", line 52, in <genexpr>
    if x.startswith("vm-","appvms/","vm-templates/")):
TypeError: slice indices must be integers or None or have an __index__ method
```

**Comment by tasket** [comment]
@tlaurion This will need one more update before fix is complete.  Working on it now.

**Comment by tasket** [comment]
@tlaurion OK, its working now.

**Comment by tasket** [comment]
There are some minor changes today also for `wyng`.

**Comment by tlaurion** [comment]
@tasket thanks, on the process of sending through --include.

Weirdly enough I now have to specify -w local on top of the prior of 0.4 dest structure:
`sudo wyng-util-qubes backup --include -w dest=file:/media/Backups/QubesOS/wyng.backup040/default/ -w local=qubes_dom0/vm-pool
`

I have read I can simply move `/media/Backups/QubesOS/wyng.backup040/default/` wherever I want and just point to it, but I am wondering how to configure this normally so I also do not have to specify `-w local`?

What changed? (from disappeared for arch-init, I was expecting to just wipe wyng metadir and arch-init from but not possible?) HAven't found [proper notes in docs, but would love to use wyng-util directly having it use the local default meta-dir and specify meta-dir only for external backups.

Also, I see a lot of 
```
Removed mis-matched snapshot for 'vm-vault-private'
Preparing full scan of 'vm-vault-private'
```

Even though they were prepared by wyng directly for the same archive. Any reason for that? 

Thanks!

**Comment by tasket** [comment]
@tlaurion The -w local issue is probably a bug that was hidden from me because I set local in /etc/wyng/wyng.ini.  If you set local in the wyng.ini that will work around the bug, and you can also set dest there, too.

The `arch-init --from` idiom is completely superseded; any time you point to an archive+location Wyng hasn't seen before it will automatically do the 'from' import.  Wyng now tracks metadata using a hash of the dest URL and the arch UUID, so its likely you can stop using 'metadir' option (although it still works).  Wyng will soon be getting some metadata age-ing (for automatic removal) and other nicer cleanup options.

Mis-matched snapshots:  The fs metadata Wyng looks at has expanded, and timestamps are also transferred to deltamaps to link them with snapshots.  Transitioning from an older Wyng version without this behavior can cause temporary mis-matching and auto-remapping; it shouldn't continue after the first round of mis-matches.

**Comment by tlaurion** [comment]
> /etc/wyng/wyng.ini. If you set local in the wyng.ini that will work around the bug, and you can also set dest there, too.

Ha! I missed that!
If the file doesn't exist, it is not automaticallyu populated?
What should I put there and what is the format?

**Comment by tasket** [comment]
See Readme section: https://github.com/tasket/wyng-backup#configuration-files
